---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authdbprod
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: authdbprod
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authdbtest
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: authdbtest