apiVersion: v1
kind: Service
metadata:
  name: auth-db-service-prod
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: authdbprod
  selector:
    app: auth-db
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-service-testing
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: authdbtest
  selector:
    app: auth-db