apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: 158.160.69.117:5000/ubersite/converter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-conv-svc