"""Init

Revision ID: a6252b62e14a
Revises: d14641028cf7
Create Date: 2023-09-13 10:50:42.551812

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6252b62e14a'
down_revision = 'd14641028cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwords')
    op.create_unique_constraint(None, 'tokens', ['id'])
    op.add_column('users', sa.Column('passwd', sqlalchemy_utils.types.password.PasswordType(max_length=1094), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'passwd')
    op.drop_constraint(None, 'tokens', type_='unique')
    op.create_table('passwords',
    sa.Column('passwd', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='passwords_pkey')
    )
    # ### end Alembic commands ###
