"""Init

Revision ID: c9afe6e12ecf
Revises: a6252b62e14a
Create Date: 2023-09-13 10:51:52.444609

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9afe6e12ecf'
down_revision = 'a6252b62e14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'passwd',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'passwd',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
